### ISSUE TITLE
OAK-D Series 2 (OAK-D-S2)

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#115]
### Start with the `why`:

Improve the mechanical of OAK-D, as being done in https://github.com/luxonis/depthai-hardware/issues/114 but without adding the cost of active depth (both in terms of $, and in terms of worse bright outdoor depth performance).

### Move to the `how`:

Reuse all of OAK-D-PRO but no-populate the active illumination components, black out the glass where these would be, and use the existing OAK-D CCM.  

### Move to the `what`:

Make an existing passive-only OAK-D successor with the mechanical advantages of https://github.com/luxonis/depthai-hardware/issues/114.  And offer fixed-focus RGB like OAK-D-Pro as well for better vibration handling.

![image](https://user-images.githubusercontent.com/32992551/137490848-129f15ab-c2d7-4de6-b27a-bfdf28808109.png)
![image](https://user-images.githubusercontent.com/32992551/137490911-5e178191-b42d-4fd3-ab62-2e520f589488.png)

This will most likely still be called `OAK-D` but will be `Series 2` or `S2` for short.

**Comment by Erol444** [comment]
Some more images
![oakd2](https://user-images.githubusercontent.com/18037362/142774191-9eade6b7-fd81-4c35-b6e7-3ffdf6f824ce.jpeg)
![oak2comparison](https://user-images.githubusercontent.com/18037362/142774196-6362eeb6-b13e-4de3-b92f-600e2db15bc4.png)

**Comment by Luxonis-Brandon** [comment]
OAK-D-S2 (top)
OAK-D-Pro (bottom)
![image](https://user-images.githubusercontent.com/32992551/146366929-1fa49047-9eaa-46c4-9bc5-99300471faaa.png)

**Comment by Luxonis-Brandon** [comment]
We're adding the capability to use USB cables that can fasten to the device.  
![image](https://user-images.githubusercontent.com/32992551/147368345-f8a4d098-90a2-43f6-9770-185cd7d61799.png)

**Comment by jcrupi** [comment]
Has IMU?

**Comment by Luxonis-David** [comment]
@jcrupi yes it does.

**Comment by Luxonis-Brandon** [comment]
![image](https://user-images.githubusercontent.com/32992551/167263393-cfc90da4-86c8-4e38-b975-31772ea0df6c.png)
https://shop.luxonis.com/collections/usb/products/oak-d-s2

Shipping to our warehouses now.
