### ISSUE TITLE
Support 155-degree FishEye OV9282 Camera

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#15]
### Start with the `why`:

As it stands now DepthAI is optimized for real-time spatial AI, so where objects are in physical space and attributes about them.  So for this, narrower field of view is desirable.

But for applications where it is desirable to self-orient and self-locate (i.e. simultaneous location and mapping - SLAM, e.g. discussion in ROS discourse [here](https://discourse.ros.org/t/opencv-ai-kit-oak/15406/15?u=luxonis-brandon)), wider field of view is of interest.  So having support for a wide field of view OV9282 camera module is of interest.

And it just so happened that Arducam reached out offering cooperation, and has a module that is ideal in terms of FOV:

- 155 degrees HFOV (166 degrees DFOV)
- Datasheet [here](https://www.arducam.com/product/arducam-ov9281-mipi-1mp-monochrome-global-shutter-camera-module-raspberry-pi/)
- Product Page [here](https://www.arducam.com/product/arducam-ov9281-mipi-1mp-monochrome-global-shutter-camera-module-raspberry-pi/)

![OV9281-155-degFOV](https://user-images.githubusercontent.com/32992551/89362867-299ad580-d68c-11ea-8467-9d856b05ae13.jpeg)

### Move to the `how`:

We are working with ArduCam to integrate this OV9282 fisheye version in with DepthAI.

### The `what`:

Support ArduCam 155-degree FishEye OV9282 Camera

**Comment by george-hawkins** [comment]
Is this a module that ArduCam are working on bringing to market?

I couldn't find such an OV9282 based module in their current lineup - the nearest I could find was this US$30 [170&deg; OV9281 based camera](https://www.arducam.com/product/arducam-ov9281-mipi-1mp-monochrome-global-shutter-camera-module-raspberry-pi/).

**Comment by Luxonis-Brandon** [comment]
Thanks @george-hawkins - great question - and thanks for catching my error(s).  So I had misinterpreted it as a OV9282 whereas it is actually OV9281, and added the link you shared to the Github issue above.

So it is 166 degree diagonal FOV and 155 horizontal FOV - so that's the discrepancy in FOV we were respectively seeing.

**Comment by ArduCAM** [comment]
@george-hawkins I gave Brandon the wrong info, it should be 166 degrees in horizontal. Extremely wide, almost fisheye and without black corners.

**Comment by ArduCAM** [comment]
Maybe I remember incorrectly, 166 degrees should be diagonal, but extremely wide and no black corners.

**Comment by slitcch** [comment]
So, could I literally just buy the camera from Arducam and stick it on my OAK-D? Or are there still some outstanding issues that need to be solved?

**Comment by Luxonis-Brandon** [comment]
These are firmware compatible as of now (which is the big hurdle) but the connector pinout for the module is different.  So a variant of the OAK-D carrier board would need to be use.  Also, for calibration accuracy, the camera internal to OAK-D are actually adhered to the board, so they are not swappable.

I am not sure if ArduCam has already made this variant.  @ArduCAM ?

**Comment by ArduCAM** [comment]
Sorry, we didn't build any drop-in replacement variant modules for OAK-D yet. 
@slitcch you might have to use BW1098FFC board to connect our OV9281 camera module with an adapter board for larger FOV. 
https://www.uctronics.com/arducam-ov9281-mipi-camera-module-1mp-global-shutter-mono-camera-130.html

**Comment by rdthompson2020** [comment]
> Sorry, we didn't build any drop-in replacement variant modules for OAK-D yet.
> @slitcch you might have to use BW1098FFC board to connect our OV9281 camera module with an adapter board for larger FOV.
> https://www.uctronics.com/arducam-ov9281-mipi-camera-module-1mp-global-shutter-mono-camera-130.html

This Q about a Wider FOV FishEye Camera hits the nail on the head for what's really needed in OAK-D
Purchased the OAK-D and waiting on it but most applications my group is interested in are FPV tracking on a Drone and aligning with footage camera. I understand there may be mapping differences for OpenCV models but if there's a way, I think this question for OAK-1 in general and later models is going to pop up a lot.

**Comment by Luxonis-Brandon** [comment]
Thanks.  So after CNY we will likely have prototypes with these modules available.  We plan to sell the ArduCam modules directly as well to make this easier for customers.

Thanks,
Brandon

**Comment by Luxonis-Brandon** [comment]
As an update @ArduCAM made a little adapter so that these wide-angle can be used directly on the BW1098OBC/BW1098OAK.  

![image](https://user-images.githubusercontent.com/32992551/105927230-d2553c80-6000-11eb-84ae-7e65c70435dc.png)
![image](https://user-images.githubusercontent.com/32992551/105927234-d4b79680-6000-11eb-9eca-e0815958a85f.png)
![image](https://user-images.githubusercontent.com/32992551/105927243-d8e3b400-6000-11eb-82e6-362933cdd446.png)
![image](https://user-images.githubusercontent.com/32992551/105927250-db460e00-6000-11eb-9531-1b3614099234.png)

**Comment by Luxonis-Brandon** [comment]
Got these working on DepthAI today with @ArduCAM 
![image](https://user-images.githubusercontent.com/32992551/106164444-32ee9180-6147-11eb-957c-e42d49fc75ff.png)

**Comment by Luxonis-Brandon** [comment]
![image](https://user-images.githubusercontent.com/32992551/106183624-af8c6a80-615d-11eb-865e-7ba533a56e59.png)
![image](https://user-images.githubusercontent.com/32992551/106183636-b2875b00-615d-11eb-8409-26a4c0aeb201.png)

**Comment by Luxonis-Brandon** [comment]
@ArduCAM just shared that they made a fully-pin-compatible 2-lane version:
![image](https://user-images.githubusercontent.com/32992551/106491533-31d5a100-6474-11eb-96a7-d3759fd093dc.png)

**Comment by Luxonis-Brandon** [comment]
Here's the comparison of the first prototype vs. the final modules:
![image](https://user-images.githubusercontent.com/32992551/108280696-c9591600-713b-11eb-9aea-326f051563b0.png)

**Comment by Luxonis-Brandon** [comment]
This is ArduCam part number B0297-C.
