### ISSUE TITLE
OAK-D W

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#152]
#### Already released, see [product documentation here](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9098w.html)

------

### Start with the `why`:

We’ve now gotten a bunch of reach-outs about something like OAK-D, but with 150 DFOV, IR-laser-dot-projection depth, and matching resolution/FOV/global shutter for the color camera.  

This is similar to this idea, https://github.com/luxonis/depthai-hardware/issues/21, which we already had on the roadmap, but with the change that apparently a lot of applications want this _and_ wide FOV, which is separately https://github.com/luxonis/depthai-hardware/issues/15.

Many folks want to use such a product on small aerial vehicles.  And as such size and weight are important.

### Move to the `how`:

ArduCam already implemented https://github.com/luxonis/depthai-hardware/issues/15 , and now produces this 150DFOV OV9282 module as a standard product for DepthAI customers, [here](https://www.arducam.com/product/arducam-1mp-ov9282-fisheye-mono-global-shutter-drop-in-replacement-for-depthai-oak-dnoir/).  So far though, this has only been used in custom products built with [OAK-SOM](https://shop.luxonis.com/collections/system-on-module-som)/etc.

We should work with ArduCam to (1) update this OV9282 to the new/standard ArduCam connector format here and (2) make a OV9782 variant with the same connector/format but that blocks IR (for good color representation).  Likely prototyping first with the existing format/connector

### ​​Move to the `what`:

Make a Wide FOV version of OAK-D Series 2 (https://github.com/luxonis/depthai-hardware/issues/115)

OAK-D W (W = Wide FOV)

- 2x OV9282 1280x800 global shutter grayscale 150 DFOV (IR capable)
- 1x OV9782 1280x800 global shutter color 150 DFOV (IR-blocking)

**Comment by Luxonis-Brandon** [comment]
![image](https://user-images.githubusercontent.com/32992551/144274116-4bc91125-2390-4db1-9c2c-d1b2d80f94b7.png)
![image](https://user-images.githubusercontent.com/32992551/144274158-c97a1e67-67c6-4d0b-b04a-280e481fbbd6.png)

**Comment by Luxonis-Brandon** [comment]
Here's more what the final version will look like.  
![image](https://user-images.githubusercontent.com/32992551/146583561-1f962150-df5a-43d5-8940-35fc1ccdf869.png)

It will have the same overall mechanical dimensions of OAK-D S2 and OAK-D Pro:
![image](https://user-images.githubusercontent.com/32992551/146583738-7ff103c4-8963-4203-ab38-de29c0268ea1.png)
![image](https://user-images.githubusercontent.com/32992551/146583766-61adbf56-a036-4edc-8e53-f2ed60b29fd4.png)

**Comment by Luxonis-Brandon** [comment]
We're adding the capability to use USB cables that can fasten to the device.  
![image](https://user-images.githubusercontent.com/32992551/147368345-f8a4d098-90a2-43f6-9770-185cd7d61799.png)

**Comment by Luxonis-Brandon** [comment]
![image](https://user-images.githubusercontent.com/32992551/157285841-10d51afe-3094-42f1-b260-2337cdc79a92.png)

**Comment by Erol444** [comment]
Already released, see [product documentation here](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9098w.html)
