### ISSUE TITLE
Pre-flashed 32GB uSD Cards for Raspberry Pi

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#161]
### Start with the `why`:

- Setting up software is annoying.  
- Compiling and/or installing software via a CLI is even more annoying.  
- And doing so on resource-constrained devices (like the Raspberry Pi) is even more annoying.  

Meanwhile, DepthAI and CEP (https://github.com/cortictechnology/cep#cortic-edge-computing-platform-cep) are AWESOME on the Pi, once you're done with Annoying^3 power above.

And for example, installing CEP alone takes 30 minutes (after you've cloned the repo).  And cloning the repo itself may take a very long time, depending on the internet connection.  And the installation process can sometimes kill SD cards (because of the compilation/etc. uses SWAP aggressively).

Given that we have thousands of customers using DepthAI and CEP on Raspberry Pi, that's a TON of time wasted by customers - waiting on things to download/compile/install.  Best-case, it's 30 minutes if folks want CEP in addition to DepthAI.

Worse, the whole purpose of CEP is to be easy.  Look at that drag-and-drop awesome:

![visual-programming](https://github.com/cortictechnology/cep/blob/main/resources/Visual-Programming.gif?raw=true) 

 It's such a buzz-kill to fight CLI stuff and wait for 30+ minutes of "Is this really going to work?" to just try it out.  

So it would be cool if there were a way to prevent that buzz-kill (the annoyance^3).  And save at least 30,000-minutes of folks time (1,000 folks, bare-minimum will use this, and it's 30 minutes for each of them).  That's 500 hours of wasted time.

Worse, often customer uSD cards are too-small to fit all the nifty CEP software (which takes 10GB or so).  So someone with an 8GB or 16GB card will discover 30+ minutes into this that it's not going to work, at all.  

And even worse, the process of trying to install actually just corrupted their already-working 8GB or 16GB uSD card.  And that's a really painful way to experience a new product, with a typical end-result of these customers being:

- The installation failed, and it nuked my Raspberry Pi OS install.  

Using a 32GB uSD card prevents this.

### Move to the `how`:

One idea is to do all this installation once to a "Golden 32GB" uSD.  And then copy it 32GB uSD cards at scale, and sell these pre-flashed uSD cards.  There are huge advantages of this:

- Each block in each flashed uSD is only written once.  Compare this with compilation/installation, where a single block could be written hundreds of thousands of times (hence wearing out the card and/or potentially killing it).
- The purchaser of the card has one step only:  Install the uSD card in the Pi.  Boom.  Done.  Check it out below, so nice:

![Insert-SD-Card](https://user-images.githubusercontent.com/32992551/142252882-8c44dc4e-8184-4cfe-8b81-a1f98bf827d8.gif)
(Ignore that the GIF is of a 16GB uSD card; I couldn't find a good GIF of a 32GB one.  Rest assured; we'll be doing 32GB.)

- There's no guessing on the customer's part if they "Did something wrong", in addition of course to saving them 30+ minutes of annoyance.

### Move to the `what`:

Make 32GB pre-flashed uSD card that has everything pre-installed.  Is there some step that we could do so a customer doesn't have to?  Then we'll do that.

**Comment by Erol444** [comment]
[Images available here](https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/raspberrypi.html#using-pre-configured-rpi-os-image) (since 2021).
