### ISSUE TITLE
please clarify OAK-D-Lite USB feature-level

### ISSUE THREAD

**Issue by diablodale** [luxonis/depthai-hardware#182]
Hi, at https://github.com/luxonis/depthai-hardware/blob/master/docs/source/pages/DM9095.rst I request text be added to declare the USB feature level for OAK-D-lite. Is it 3.1, 3.2, gen1, gen2, etc.

As comparison, OAK-D docs at https://github.com/luxonis/depthai-hardware/blob/master/docs/source/pages/BW1098OAK.rst clearly states twice "USB 3.1 Gen1 (Type-C)".

This knowledge is requested so that coding+testing of app correctly bounds the USB feature-level based on the specific Luxonis device.

**Comment by Luxonis-Brandon** [comment]
Thanks great idea/request.  CC: @Luxonis-David to provide this exactly.

**Comment by Luxonis-David** [comment]
PR #183

**Comment by Luxonis-David** [comment]
@diablodale do you think we should close this issue based on the PR above?

**Comment by diablodale** [comment]
Yes, that's super. Looks good to me on live site. ;-)
