### ISSUE TITLE
IR Dot Projector + IR-capable Global Shutter Grayscale

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#20]
### Start with the `why`:

For high-granularity depth and for support of low-visual-interest objects, having a dot projector to augment these surfaces with visual interest is extremely beneficial.

### Move to the `how`:

Leverage IR-capable camera modules (either visible-light + IR or IR-bandpass, such as the upcoming ArduCam OV9282 modules) and an IR dot projector pair (and timing/strobe circuitry for more efficient power use) to make an active-illumination variant of DepthAI.

### Move to the `what`:

Support active illumination on DepthAI.

**Comment by eric-schleicher** [comment]
this is great.  how much are the dot projectors?

**Comment by Luxonis-Brandon** [comment]
I don't -think- we can share.  Or at least we haven't asked.  But here they are: 
![image](https://user-images.githubusercontent.com/32992551/99460904-f8b67780-28ed-11eb-9d24-7a4622600168.png)

We're behind on board design help right now.  So we haven't made a reference with these yet, but we're hiring so we should be able to early next year.  

And then need to go through laser safety certification.

**Comment by Ravislmn** [comment]
Any update ?

**Comment by Luxonis-Brandon** [comment]
The laser safety certification is looking to be a blocker.  We engaged with a consultant on this, but it kind of stopped there.  So we are trying to re-kick it off.

**Comment by Luxonis-Brandon** [comment]
This is now implemented in https://github.com/luxonis/depthai-hardware/issues/114
