### ISSUE TITLE
Could you add Y-Adapter (KS) STEP file to this repo.

### ISSUE THREAD

**Issue by bgilreath** [luxonis/depthai-hardware#216]
The exterior is most necessary to integrate into other designs. This would be for the OAK-D-Lite. Thanks!

**Comment by Luxonis-Brandon** [comment]
Good idea.  I thought we had this published but asking internally.

**Comment by Luxonis-David** [comment]
@bgilreath you can find dedicated folder for Y-adapter [here](https://github.com/luxonis/depthai-hardware/tree/master/DM6010_Y-adapter).
Step files for the whole product are in [Mechanical folder](https://github.com/luxonis/depthai-hardware/tree/master/DM6010_Y-adapter/Mechanical), in case you would need a step file of a PCBA it is in [3D Models folder](https://github.com/luxonis/depthai-hardware/tree/master/DM6010_Y-adapter/3D_Models).

**Comment by bgilreath** [comment]
Thank you! Is it appropriate to also link to it on the OAK-D-Lite page under the 3D models section? https://docs.luxonis.com/projects/hardware/en/latest/pages/DM9095.html

**Comment by Luxonis-David** [comment]
@Erol444 thoughts on above?
