### ISSUE TITLE
PR: Step files for BW1098OBC BW1093 in OAK Cameras

### ISSUE THREAD

**Issue by ZurMaD** [luxonis/depthai-hardware#23]
Hello there, I build a simple files for a version of BW1098OBC for people who just want a model with real dimensions and no details, maybe the Depth AI can add to documentation to support community

![image](https://user-images.githubusercontent.com/28235457/96848731-6ae48b00-141a-11eb-81d8-6dcb25b8aca6.png)

Dimensions according to https://github.com/luxonis/depthai-hardware/tree/master/BW1098OBC_DepthAI_USB3C

Public link of the files https://grabcad.com/library/bw1098obc-for-oak-d-stereo-camera-1

Also, for BW1093

![image](https://user-images.githubusercontent.com/28235457/96848984-af702680-141a-11eb-8ec8-cbe31cb8324d.png)

Public link of the files https://grabcad.com/library/bw1093-for-oak-1-color-camera-opencv-1

**Comment by Luxonis-Brandon** [comment]
Thanks @ZurMaD !  So one note on OAK-1 is that the fins actually do go the opposite direction:
![image](https://user-images.githubusercontent.com/32992551/96947525-ab86e780-14a0-11eb-81ed-fefc9c1d4931.png)

**Comment by ZurMaD** [comment]
Thanks for the feedback, I tried to fix it. It's not exactly the same heatsink fin, but I think it's ok. Next week, I'll upload new versions of two models direct to GrabCad.

![OAK11](https://user-images.githubusercontent.com/28235457/97053053-c8c2c100-1547-11eb-8f9f-d63ecfffbb77.png)

**Comment by Luxonis-Brandon** [comment]
Thanks @ZurMaD !
