### ISSUE TITLE
OAK-FFC-6P - 6-Port OAK FFC

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#248]
### Start with the `why`:

With the new OAK-SoM-MAX ([Series 3](https://docs.luxonis.com/projects/hardware/en/latest/pages/articles/oak-s3.html); [here](https://docs.luxonis.com/projects/hardware/en/latest/pages/DM3399.html#oak-som-max)) it is possible to connect 6x cameras.

For prototyping it is often desirable to have a way to connect various cameras/image sensors/etc.  So an equivalent of our OAK-FFC-3P (which works with OAK-SoM and OAK-SoM-IoT) and OAK-FFC-4P (which works with OAK-SoM-Pro and OAK-SoM-Pro-KB) would be quite useful.

### Move to the `how`:

Leverage the OAK-SoM-MAX module to make an OAK-FFC-6P which supports 6 FFC cameras.

### Move to the `what`:

 - 6x 2-lane MIPI interfaces (note each can still support 4k/60FPS on IMX378 and IMX477/IMX577).
 - uSD Card Slot
 - OAK-SoM-MAX connection
 - IMU
 - USB3.1
 - IO including framesync
 - Coincell battery slot for Linux RTC

**Comment by Erol444** [comment]
Some renders of the board:
![image](https://user-images.githubusercontent.com/18037362/169587026-73100c7a-7583-4f8d-96e8-ae99143d0818.png)
![image](https://user-images.githubusercontent.com/18037362/169587065-e9db80b3-ccab-4bc4-a047-e270f26485c9.png)
![image](https://user-images.githubusercontent.com/18037362/169587074-3525e62e-a682-4b23-95ee-31718708f85d.png)
![image](https://user-images.githubusercontent.com/18037362/169587085-5df37780-0115-47fd-b8f8-52739f0e6d8a.png)

**Comment by Erol444** [comment]
Hello @madgrizzle , There should be support to use any pair of the 6 cams to run stereo - we have to ask the HW engineer why he labeled it this way:)

**Comment by Luxonis-Brandon** [comment]
![IMG_20220704_151358](https://user-images.githubusercontent.com/32992551/177166323-151d3a79-8fb3-4c54-968e-627547ca13f7.jpg)
![IMG_20220704_151333](https://user-images.githubusercontent.com/32992551/177166317-f5f55699-e72c-44fa-827c-86c9ea28f818.jpg)
