### ISSUE TITLE
Cameras - How to handle things like - Headlight Glare

### ISSUE THREAD

**Issue by yashhema** [luxonis/depthai-hardware#25]
Hello,
Have you thought about - how to handle headlight glare and WLC and BLC (which are usually present in CCTV)

regards

**Comment by Luxonis-Brandon** [comment]
Hi @yashhema ,

So one of the camera modules that seems well suited for this (for which we have drivers) is the IMX390, [here](https://www.sony-semicon.co.jp/products/common/pdf/IMX390.pdf).  

Here are the other modules for which we have driver support.  The check-marked ones are ones we have actually tried out.

- [ ] IMX214
- [ ] IMX283
- [ ] IMX334
- [x] IMX378
- [x] IMX477
- [x] OV9282 
- [x] OV9782
- [x] OV9281
- [ ] OV7750/OV7251
- [ ] IMX412
- [ ] SC2232H
- [ ] OV2735
- [ ] OV5645
- [ ] IMX390
- [ ] SC5335
- [ ] IMX363
- [ ] SC8238
- [ ] OV12895

And the others theoretically would be usable.  But we'd need to make adapter boards for them first and then see about integrating the drivers into our Gen2 Pipeline builder (https://github.com/luxonis/depthai/issues/136).

Thoughts?

Thanks,
Brandon
