### ISSUE TITLE
Step Model For Oak D Lite

### ISSUE THREAD

**Issue by sgstreet** [luxonis/depthai-hardware#282]
Can you add the Step CAD Model for the Oak D Lite?  I would like to design a custom camera mount for my robot and would like to generate simplified Collada files uses in ROS Rvis.

**Comment by Erol444** [comment]
Hi @sgstreet , is the link below what you are looking for?
https://github.com/luxonis/depthai-hardware/tree/master/DM9095_OAK-D-LITE_DepthAI_USB3C/Mechanical

**Comment by sgstreet** [comment]
@Erol444 Yes, prefect,  Sorry about that my confusion, from the readme.md I thought that was the Lego mount.
