### ISSUE TITLE
Dae or stl for Oak-D-Lite model

### ISSUE THREAD

**Issue by mohamedlaminetazir** [luxonis/depthai-hardware#302]
Can you add the Collada Model for the Oak D Lite? I would like to integrate it into the gazebo model of my robot

**Comment by Erol444** [comment]
Hi @mohamedlaminetazir ,
We apologize for the delay. You can find the required [file here](https://github.com/luxonis/depthai-ros/tree/ros-release/depthai_bridge/urdf/models). Let us know if this helps!
Thanks, Erik

**Comment by mohamedlaminetazir** [comment]
it helps, Thanks for your feedback.
