### ISSUE TITLE
BW1098FFC with Onboard IMU and ArduCam FFC connections

### ISSUE THREAD

**Issue by Luxonis-Brandon** [luxonis/depthai-hardware#36]
### Start with the `why`:

The ArduCam OV9281 and IMX477 and other modules that offer M12, wide FOV, C-mount, etc. are extremely useful for making depthai applicable for varieties of use-cases.  So it would be beneficial to have direct support for them one the BW1098FFC without [any adapters](https://github.com/luxonis/depthai-hardware/tree/master/BW0253_R0M0E0_RPIHQ_ADAPTER).

Also, in many applications, the IMU present on the OAK-D, BW1092, etc. would be beneficial, so when modifying this board, it would make sense to add the IMU.

### Move to the `how`:

Pull the IMU from the BW1098OAK and change the FFC adapter connectors to be what ArduCam uses on their FFC cameras.

### Move to the `what`:
- Add 1A 3.3V regulator from 1092 design to power ArduCam camera modules
- Change all 3 FFC connectors to https://www.molex.com/molex/products/part-detail/ffc_fpc_connectors/5052782233 to match updated connectors on DM1098FFC, etc. 
- Update the pinout for all 3 connectors to match the RPI/Arducam Pinout. The two stereo cameras will remain 2-lane MIPI while the RGB camera will match the full 4-lane configuration. 
- Level shifter for I2C interface (1.8V <--> 3.3V)
- Completely new board name (DM1090?) to distinguish from other FFC versions with 20/26 pin FFC interfaces.

**Comment by Luxonis-Brandon** [comment]
So ArduCam actually had independently proposed making this yesterday.  So they are already building it.  :-)

**Comment by Luxonis-Brian** [comment]
Updated this issue to add more detail to the `what` section

**Comment by Luxonis-Brandon** [comment]
Thanks!  And I think ArduCam submitted designs to us with these changes already... did they?

**Comment by Luxonis-Brandon** [comment]
This has now been implemented and ArduCam just built a prototype board and verified that it all works!

![image](https://user-images.githubusercontent.com/32992551/110732767-01ef8b00-81e2-11eb-9723-b090de1c7af3.png)

**Comment by Luxonis-Brandon** [comment]
And the PR for this is here: https://github.com/luxonis/depthai-hardware/pull/41

**Comment by Luxonis-David** [comment]
Pull request #41 is for old interface with more robust connectors, PR for 26-pin interface with IMU support is here #50.

**Comment by Luxonis-Brandon** [comment]
The fully updated versions just finished being made.  DM1090FFC is the new name, changed from 1098FFC since these have different connectors and we will continue to sell the old ones for those than need them on existing installations.
![DM1090FFC_R0M0E0 pcba](https://user-images.githubusercontent.com/32992551/112725093-056e5c00-8edc-11eb-892d-20df2d67cdab.jpg)
![BW2099_R1M1E1 pcb](https://user-images.githubusercontent.com/32992551/112725095-07381f80-8edc-11eb-8d6b-086bee1c2dc9.jpg)

**Comment by Luxonis-David** [comment]
Resultant files for this issue can be found on above linked pull-request or on the link below: 
[DM1090FFC_DepthAI_USB3](https://github.com/luxonis/depthai-hardware/tree/master/DM1090FFC_DepthAI_USB3)
