### ISSUE TITLE
[Documentation] rasp pi image is 7z, not zip.  how to properly etch onto sd?

### ISSUE THREAD

**Issue by stuartcrobinson** [luxonis/depthai-hardware#427]
docs say 

> Click on the Flash from file and select the .zip image you have previously downloaded.

but the image is a .7z file, which balenaEtcher doesn't seem to recognize.  

<img width="195" alt="image" src="https://github.com/luxonis/depthai-hardware/assets/12928716/f900bbba-63df-42a5-84c7-b610226a6bc6">

not sure if i need to decompress it and load directly or if that will cause problems? or use a different etcher? 

https://docs.luxonis.com/projects/hardware/en/latest/pages/guides/raspberrypi/

**Comment by Erol444** [comment]
Hi @stuartcrobinson ,
Unzip the file, which should contain the image, which balenaEtcher can use.
