### ISSUE TITLE
BW1099EMB Heatsink / 3D STEP

### ISSUE THREAD

**Issue by AndrewKeene** [luxonis/depthai-hardware#44]
Hi DepthAI team, 

I see the 3D models of the carrier boards have the heatsink model integrated, but I'm not seeing the heatsink in the standalone SoM models.  Is there a 3D STEP available for the BW1099EMB with the heatsink mounted, and if not is there a STEP just for the heatsink available?  Thank you!

**Comment by Luxonis-Brandon** [comment]
Thanks @AndrewKeene ,

Good point.  We should add a version of each that includes the heatsink, for each SOM [here](https://github.com/luxonis/depthai-hardware/tree/master/SoMs).  @Luxonis-David - could you please do so when you have a second?

And in the meantime I'll see if I can find the STEP file for the heatsink by itself.

Thanks again,
Brandon

**Comment by Luxonis-Brandon** [comment]
Here is the step file for the heatsink @AndrewKeene :  

[https://drive.google.com/file/d/16t6zTeiB6AHo2_8wcAw2twctY_KXrG8R/view?usp=sharing](https://drive.google.com/file/d/16t6zTeiB6AHo2_8wcAw2twctY_KXrG8R/view?usp=sharing)

![image](https://user-images.githubusercontent.com/32992551/108549636-a731d600-72aa-11eb-8b80-aa1aca153b09.png)


We'll get it added to the Git directories and with the SOM together next week as well.

Thoughts?

Thanks,
Brandon

**Comment by Luxonis-David** [comment]
I have added step files for each SOM [here](https://github.com/luxonis/depthai-hardware/tree/master/SoMs).
Also updated readme.

**Comment by Luxonis-Brandon** [comment]
Thanks!

**Comment by AndrewKeene** [comment]
Thanks guys!
