### ISSUE TITLE
Can I use a code from Luxonis on a real Sense camera?

### ISSUE THREAD

**Issue by DanSpinThaBin** [luxonis/depthai-hardware#454]
https://github.com/luxonis/depthai-experiments/tree/master/gen2-gaze-estimation

This is the code I got from this website:
https://docs.luxonis.com/en/latest/ 

Would I be able to use these codes if I have a D435i depth tracking camera from Real Sense?
If not what would I have to change?

**Comment by Erol444** [comment]
Hi @DanSpinThaBin ,
No, you wouldn't be able to. You would need to change everything - as depthai library (which the whole file uses) can only be used on our cameras.

**Comment by DanSpinThaBin** [comment]
I see thank you.
