### ISSUE TITLE
Bad content under dev-blobconverter.luxonis.com

### ISSUE THREAD

**Issue by khssnv** [luxonis/depthai-hardware#472]
Hello. RAE documentation ([here](https://github.com/luxonis/depthai-hardware/blob/master/docs/source/pages/rae.rst#running-nn-on-rae)) contains a link to https://dev-blobconverter.luxonis.com/ which shows an unexpected content (some PC parts shop). Please find a screenshot under a toggle below.

<details>
<summary>https://dev-blobconverter.luxonis.com/</summary>

![image](https://github.com/luxonis/depthai-hardware/assets/833019/d0d8ae1b-94fa-4923-8b3c-7209b3369773)
</details>

**Comment by Luxonis-Vlad** [comment]
Thanks for the report,  we've just updated the docs.
