### ISSUE TITLE
Question about IR Projector

### ISSUE THREAD

**Issue by HasanTheSyrian** [luxonis/depthai-hardware#489]
Hello, I'm trying to use the same IR dot project you use but I'm finding the datasheet a bit vague.

I found the Belago 1.1 used in one of your [schematics](https://github.com/luxonis/depthai-hardware/blob/4f95bf5783d0b972b01e470fb79bf268c115c31d/NG6011_Dot_projector/Docs/Schematic%20PDF/Production.PDF), and I have a few questions:

Are we expected to provide the resistance for the interlock mechanism? From what I understood it has its own resistance. In the schematic the interlock pins are connected to 300 and 360 kOhm resistors, why that specifically? 

Why are the interlock pins supplied with 5V? The datasheet mentions that the interlock is a "conductive loop" but doesn't say that we should supply the voltage and it also has no mention of what this voltage should/shouldn't be.

In the schematic above the Belago symbol, it says that the Voltage threshold is set to 2.475V, from where did you get this number?

Why is an LED driver used? Is it to flash the dot projector on and off continuously? Or flash once (like taking a photo)? Why can't it stay powered?

What is the output voltage from LED driver going into the IR projector?

![image](https://github.com/user-attachments/assets/65a4b3e1-a8b1-44f5-b1cf-10cb2919b864)

**Comment by Erol444** [comment]
Hi @HasanTheSyrian , I believe we mostly just followed the recommended setup, so there's no "secret sauce" from us here. Closing it as it's not directly related to OAK cameras (if that's not the case, please send an email to support@luxonis.com).
