### ISSUE TITLE
OAK-D Lite PCBA STEP is outdated

### ISSUE THREAD

**Issue by chobitsfan** [luxonis/depthai-hardware#490]
There is a BMI270 installed in current version of OAK-D lite. It seems PCBA file in https://github.com/luxonis/depthai-hardware/tree/master/DM9095_OAK-D-LITE_DepthAI_USB3C is outdated? Would you update it? Thank you very much

**Comment by Erol444** [comment]
Hi @chobitsfan , the OAK-D-Lite itself isn't opensource, as it's chip-down design - which PCBA file are you referring to?

**Comment by chobitsfan** [comment]
Hi @Erol444 Thank you for replying. I am refering to https://oak-files.fra1.cdn.digitaloceanspaces.com/OAK-D-Lite/DM9095_PCBA.STEP

**Comment by chobitsfan** [comment]
Hi @Erol444 Thank you so much for updating.
